-
  name: Copy Code Files
  hosts: webworkers
  tasks:
          - name: Copy Files
            copy:
                    src: /tmp/second.html
                    dest: /tmp
          - name: 'Cat command module' 
            command: cat /etc/hosts 
          -
            name: 'Update entry into /etc/resolv.conf'
            lineinfile:
                path: /etc/resolv.conf
                line: 'nameserver 10.1.250.10'
          -
            name: 'Executing script'
            script: /tmp/install.sh
  name: User Creation 
  hosts: worker1
  tasks: 
          - name: User creation on worker1
            user:
                    name: ram
                    password: Ram@2143
                    uid: 1234  
             
